In [25]:
import numpy as np
import scipy.linalg as linalg

** Define Matrices using the numpy array class.**

In [8]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[1,2],[3,4]])

In [10]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
B

array([[1, 2],
       [3, 4]])

** Matrix multiplication **

In [16]:
C = A@B
C

array([[ 7, 10],
       [15, 22],
       [23, 34]])

** Matrix multiplication element-wise **

In [17]:
A*C

array([[  7,  20],
       [ 45,  88],
       [115, 204]])

** Matrix Transpose ** 

In [24]:
A.conj().T

array([[1, 3, 5],
       [2, 4, 6]])

 ** Matrix times scalar **

In [26]:
A*2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

** Inverse Matrix **

In [36]:
iB = linalg.pinv(B)
iB

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [38]:
B@iB

array([[ 1.00000000e+00, -6.66133815e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

** Identity Matrix **

In [43]:
id5 = np.eye(5)
id5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

** Ones Matrix **

In [48]:
ones5x4 = np.ones((5,4))
ones5x4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

** Zeroes Matrix **

In [50]:
zeroes5x4 = np.zeros((5,4))
zeroes5x4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

** Power (element wise)**

In [54]:
A**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]], dtype=int32)

** Import data **

In [31]:
data = np.genfromtxt('ex1data2.txt', delimiter=',')
data

array([[2.10400e+03, 3.00000e+00, 3.99900e+05],
       [1.60000e+03, 3.00000e+00, 3.29900e+05],
       [2.40000e+03, 3.00000e+00, 3.69000e+05],
       [1.41600e+03, 2.00000e+00, 2.32000e+05],
       [3.00000e+03, 4.00000e+00, 5.39900e+05],
       [1.98500e+03, 4.00000e+00, 2.99900e+05],
       [1.53400e+03, 3.00000e+00, 3.14900e+05],
       [1.42700e+03, 3.00000e+00, 1.98999e+05],
       [1.38000e+03, 3.00000e+00, 2.12000e+05],
       [1.49400e+03, 3.00000e+00, 2.42500e+05],
       [1.94000e+03, 4.00000e+00, 2.39999e+05],
       [2.00000e+03, 3.00000e+00, 3.47000e+05],
       [1.89000e+03, 3.00000e+00, 3.29999e+05],
       [4.47800e+03, 5.00000e+00, 6.99900e+05],
       [1.26800e+03, 3.00000e+00, 2.59900e+05],
       [2.30000e+03, 4.00000e+00, 4.49900e+05],
       [1.32000e+03, 2.00000e+00, 2.99900e+05],
       [1.23600e+03, 3.00000e+00, 1.99900e+05],
       [2.60900e+03, 4.00000e+00, 4.99998e+05],
       [3.03100e+03, 4.00000e+00, 5.99000e+05],
       [1.76700e+03, 3.00000e+00, 2.5290

In [33]:
data.shape

(47, 3)

** Select rows or columns **

In [67]:
seccol = data[:,2]
seccol

array([399900., 329900., 369000., 232000., 539900., 299900., 314900.,
       198999., 212000., 242500., 239999., 347000., 329999., 699900.,
       259900., 449900., 299900., 199900., 499998., 599000., 252900.,
       255000., 242900., 259900., 573900., 249900., 464500., 469000.,
       475000., 299900., 349900., 169900., 314900., 579900., 285900.,
       249900., 229900., 345000., 549000., 287000., 368500., 329900.,
       314000., 299000., 179900., 299900., 239500.])

In [70]:
secrow = data[2,:]
secrow

array([2.40e+03, 3.00e+00, 3.69e+05])

In [72]:
# note one directional vectors are not nx1  or 1xn they are just n
print(seccol.shape)
print(secrow.shape)

(47,)
(3,)


(47, 1)

** Concatenates columns **

In [75]:
# Prepare a ones vector of the same size to be appended to the data array
rows = data.shape[0]
onesnx1=np.ones((rows,1))
onesnx1.shape

# Three alternatives:
X = np.c_[onesnx1,data]
X = np.hstack((onesnx1,data))
X = np.concatenate((onesnx1,data),1)
X

array([[1.00000e+00, 2.10400e+03, 3.00000e+00, 3.99900e+05],
       [1.00000e+00, 1.60000e+03, 3.00000e+00, 3.29900e+05],
       [1.00000e+00, 2.40000e+03, 3.00000e+00, 3.69000e+05],
       [1.00000e+00, 1.41600e+03, 2.00000e+00, 2.32000e+05],
       [1.00000e+00, 3.00000e+03, 4.00000e+00, 5.39900e+05],
       [1.00000e+00, 1.98500e+03, 4.00000e+00, 2.99900e+05],
       [1.00000e+00, 1.53400e+03, 3.00000e+00, 3.14900e+05],
       [1.00000e+00, 1.42700e+03, 3.00000e+00, 1.98999e+05],
       [1.00000e+00, 1.38000e+03, 3.00000e+00, 2.12000e+05],
       [1.00000e+00, 1.49400e+03, 3.00000e+00, 2.42500e+05],
       [1.00000e+00, 1.94000e+03, 4.00000e+00, 2.39999e+05],
       [1.00000e+00, 2.00000e+03, 3.00000e+00, 3.47000e+05],
       [1.00000e+00, 1.89000e+03, 3.00000e+00, 3.29999e+05],
       [1.00000e+00, 4.47800e+03, 5.00000e+00, 6.99900e+05],
       [1.00000e+00, 1.26800e+03, 3.00000e+00, 2.59900e+05],
       [1.00000e+00, 2.30000e+03, 4.00000e+00, 4.49900e+05],
       [1.00000e+00, 1.3

** Mean of each column in an array **

In [83]:
data.mean(0)

array([2.00068085e+03, 3.17021277e+00, 3.40412660e+05])

In [85]:
data.std(0)

array([7.86202619e+02, 7.52842809e-01, 1.23702536e+05])